// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtMGbDxCsuDSiVv9UNskPs3bykPWW4t9o',
    appId: '1:563430948771:web:79e1dd9786fa550db8a416',
    messagingSenderId: '563430948771',
    projectId: 'pick-my-snacks',
    authDomain: 'pick-my-snacks.firebaseapp.com',
    storageBucket: 'pick-my-snacks.firebasestorage.app',
    measurementId: 'G-E4TEVVV8J9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvTS_N05If3Gwd2Mq9mo2mX5BCvWJpNGQ',
    appId: '1:563430948771:android:f2a1f82d7d48f93db8a416',
    messagingSenderId: '563430948771',
    projectId: 'pick-my-snacks',
    storageBucket: 'pick-my-snacks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwh6M23i5eEIjUgc72bHMn7e3QHur9qlQ',
    appId: '1:563430948771:ios:a541a873a4e34f32b8a416',
    messagingSenderId: '563430948771',
    projectId: 'pick-my-snacks',
    storageBucket: 'pick-my-snacks.firebasestorage.app',
    iosBundleId: 'com.example.pickMySnacks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwh6M23i5eEIjUgc72bHMn7e3QHur9qlQ',
    appId: '1:563430948771:ios:a541a873a4e34f32b8a416',
    messagingSenderId: '563430948771',
    projectId: 'pick-my-snacks',
    storageBucket: 'pick-my-snacks.firebasestorage.app',
    iosBundleId: 'com.example.pickMySnacks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtMGbDxCsuDSiVv9UNskPs3bykPWW4t9o',
    appId: '1:563430948771:web:a5c66647a2a544a2b8a416',
    messagingSenderId: '563430948771',
    projectId: 'pick-my-snacks',
    authDomain: 'pick-my-snacks.firebaseapp.com',
    storageBucket: 'pick-my-snacks.firebasestorage.app',
    measurementId: 'G-MBRQWQEK0D',
  );
}
